### ISSUE TITLE
Unable to resolve material-icons.css

### ISSUE THREAD

**Issue by minnesota-josh** [algoz098/vue-player#18]
Just tried adding to my project, at runtime:

Error: Can't resolve '~material-design-icons/iconfont/material-icons.css' in '/Users/jlonganecker/lf-headless/node_modules/@algoz098/vue-player/src/components'

**Comment by algoz098** [comment]
Hi @minnesota-josh i'm without time to handle this right now, if you want make a PR i will approve it

**Comment by Guoxweii** [comment]
+1

**Comment by ptsneves** [comment]
Is this still applicable? I am able to build with `npm run-script build`. I believe this can be closed.
