### ISSUE TITLE
Cannot load the module

### ISSUE THREAD

**Issue by danieljbrennan** [algoz098/vue-player#3]
``` 
import vuePlayer  from  '@algz098/vue-player'

  export default {
    name: "Video",
    components: {
      vuePlayer
    },
```

`Error: Can't resolve '@algz098/vue-player'`

**Comment by algoz098** [comment]
Hi @danieljbrennan sorry for that happen!

Could you try to import using `@algoz098/vue-player` seems like i mistyped a missing o there.

Please report if it works so i closed it and implement a fix on the documentation

Thanks

**Comment by danieljbrennan** [comment]
```
This dependency was not found:

* iphone-inline-video in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@algoz098/vue-player/src/components/videoPlaceholder.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save iphone-inline-video
```
was the new error after correcting the typo. So I installed iphone-inline-video.
Now I can see the player, but when I click play there's a js console error:
```
player.vue?ec7e:442 Uncaught (in promise) DOMException
atPlayPause @ player.vue?ec7e:442
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
```

**Comment by algoz098** [comment]
Exist a error in package.jsondependencies.

I have publish a fix for that, can you reinstall the package, and re try?

Thanks!

**Comment by danieljbrennan** [comment]
new errors
![image](https://user-images.githubusercontent.com/5805841/65476346-704a5d00-de37-11e9-833f-49b90dcde1d9.png)

**Comment by algoz098** [comment]
Can you provide the code where the lib is used?

It seems like you are missing some vars and methods.
