### ISSUE TITLE
consult: How to solve the problem of slow loading of large files?

### ISSUE THREAD

**Issue by 3192225267** [algoz098/vue-player#30]
The file I need to play is about an hour and a half, and it takes a long time to load every time I enter the page. Is there any way to make my pressing surface load faster?

**Comment by 3192225267** [comment]
<div id="app">
    <div class="player-container">
      <vue-core-video-player ref="video"
        src="http://qiniuyun.bestliu.cn/晴天.mp4"
      ></vue-core-video-player>
    </div>
  </div>

**Comment by 3192225267** [comment]
`<template>
  <div id="app">
    <div class="player-container">
      <vue-core-video-player ref="video"
        src="http://qiniuyun.bestliu.cn/晴天.mp4"
      ></vue-core-video-player>
    </div>
  </div>
</template>
`

**Comment by 3192225267** [comment]
src="http://qiniuyun.bestliu.cn/晴天.mp4"

**Comment by 3192225267** [comment]
What I use is to store it on a cloud server, and then request its storage address, is this way bad?
src="http://qiniuyun.bestliu.cn/晴天.mp4"

**Comment by 3192225267** [comment]
What I use is to store it on a cloud server, and then request its storage address, is this way bad?
src="http://qiniuyun.bestliu.cn/%E6%88%90%E4%B8%BA%E5%9F%BA%E7%9D%A3%E7%B2%BE%E5%85%B5%E7%9A%84%E6%9D%A1%E4%BB%B6.mp4"

**Comment by algoz098** [comment]
The vue-player is act just a <video> tag wrapper, so if it works in a video tag, it should work in the vue-player, try to see if the server is not tryng to load all the file before allow you to play it.

Besides, you can always PR a change to it`s behaivior

**Comment by ptsneves** [comment]
The issue is you are likely using a video file directly on the src field. To get better experiences you should use HLS or DASH sources.
