### ISSUE TITLE
Conflict with Bootstrap class "container"

### ISSUE THREAD

**Issue by deni5n** [algoz098/vue-player#5]
When BootstrapVue is used, the class "container" defined in the file "videoPlaceholder.vue" overrides its own Bootstrap class and everything breaks.

For correction, I simply replaced the class name "container" in the file "videoPlaceholder.vue" with "container-player"

**Comment by emipmttt** [comment]
same, with "button" class name button, you could change class names like vue-player-button or vue-player conflict, 'couse the current names are very generic
